### ISSUE TITLE
NPM package missing code

### ISSUE THREAD

**Issue by mosheduminer** [ragokan/solform#1]
Hey, the latest NPM package (1.0.3) is missing the code and type files.
I downgraded to 1.0.2 for now.

**Comment by ragokan** [comment]
> Hey, the latest NPM package (1.0.3) is missing the code and type files. I downgraded to 1.0.2 for now.

Ah, I didn't know that. Let me create a new version for it. Thanks for letting me know.

**Comment by ragokan** [comment]
Just published 1.0.4, please try it again and give a feedback.
https://www.npmjs.com/package/solform

**Comment by mosheduminer** [comment]
Yup that works, thanks.

**Comment by debpalash** [comment]
same happening with solid 1.4.8 and solform 1.0.5

**Comment by ragokan** [comment]
> same happening with solid 1.4.8 and solform 1.0.5

Weird, I will update the package today.
