### ISSUE TITLE
Alter type definition for SolFormElement to include HTMLTextAreaElement

### ISSUE THREAD

**Issue by shodevacc** [ragokan/solform#7]
Typescript compiler currently throws an error while using solform with the textarea tag. This fix simply requires to change the type definition of the SolFormElement as the actual functionality does not change.

Current
```
export declare type SolFormElement = HTMLInputElement | HTMLSelectElement;
```

Proposed change
```
export declare type SolFormElement = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;
```

**Comment by ragokan** [comment]
Hello, may you simply do that and make a pull request for that? Because you found the solution, that would be more appropriate.

**Comment by shodevacc** [comment]
I have made the pull request. Cheers 👍
